### ISSUE TITLE
Init.lua

### ISSUE THREAD

**Issue by zena1** [buffet/kiwmi#19]
[..kiwmi/luak/luak.c:238] error running config cannot open /home/build/.config/kiwmi/init.lua no such file or directory 
[..kiwmi/main.c:90] fail to run server

**Comment by buffet** [comment]
kiwmi has no default config file, and launching without a config is considered an error, as it most probably is not what you want (logged into a blank, green screen, unable to do anything).

Hence to use kiwmi you need to specify a config file (empty is fine, if the above thing is really what you want for some reason).

In the future a repo with a few examples is planned, at the moment I'll just link you this minimal floating config though: https://gist.github.com/buffet/ae23f111274032b2d599374112a8adff. Enjoy!

**Comment by ildar** [comment]
example `init.lua` is still very much demanded.

**Comment by buffet** [comment]
> example `init.lua` is still very much demanded.

See the link I posted above.

**Comment by ildar** [comment]
I mean in repo. Would you add it in? It looks good at first sight.

**Comment by ahmadraniri1994** [comment]
Yeah, lack of example is deal-breaker IMO... though there is a documentation.

**Comment by lidgnulinux** [comment]
Hey, I found nice example : https://github.com/dacyberduck/kiwmi-config
