### ISSUE TITLE
With two outputs, views only flash shortly when they are being updated

### ISSUE THREAD

**Issue by tiosgz** [buffet/kiwmi#21]
When executing `kiwmi` (https://github.com/buffet/kiwmi/commit/33cbb7e3d859775b8c7015916cf4c2dd1b7cc5f3, latest commit as of now) with two outputs, clients/views are only visible the moment they’re updating, then they disappear again.

I’m using your [minimal floating config](https://gist.github.com/buffet/ae23f111274032b2d599374112a8adff) with only a few changes: terminal (alacritty), dragging views with MMB and resizing with RMB, no `swaybg` running.

If you need to know more I’m happy to try getting more info, but unfortunately I can’t write C/wlroots.

**Comment by buffet** [comment]
Just to make it easier to track this down:
When you run kiwmi with only one output that does not happen, right?

**Comment by tiosgz** [comment]
> When you run kiwmi with only one output that does not happen, right?

Right, this is a multi-output-only issue.

**Comment by buffet** [comment]
Alright thank you, I'll look into it later probably.

**Comment by tiosgz** [comment]
Also it seems like one output mirrors the other, but not vice versa. No, it’s even stranger.

With laptop’s internal display at 1920x1080 and external monitor at 1680x1050:

1. Open a terminal. It shows only on the external monitor, top left edge.
2. Move the terminal so that its right edge is out of the external monitor. The part that’s missing shows on both outputs, on the left edge.
3. Move the terminal so that its right edge is out of the laptop display. The main part of the terminal is still visible on both outputs, but the same goes for the ‘missing’ part that should be invisible.

When moving the terminal so that it should be partly behind any other (top, left, bottom) edge of the external monitor, it behaves as expected (i.e. that part of the terminal is really hidden).

**Comment by tiosgz** [comment]
I should have tried configuring the outputs earlier, but anyway:

* If the outputs are both at `[0, 0]` everything is almost normal. I can open a terminal, move it around, it’s visible all the time and doesn’t show parts behind the outputs’ edges. The only problem is when the mouse cursor is outside the terminal (i.e. is hovering over the background), when the terminal is completely invisible (no flickering).
* If the outputs are mirroring each other, but e.g. `1680x1050@[0, 0]` and `1920x1080@[100, 0]`, the terminal not only flickers (as described above), but also every time it would update it slides to the left (I think 100px each time it shows) and upon next update it’s at its usual position.
* If the outputs are completely separate (as happens with `auto()`), the behaviour is as described above.

**Comment by tiosgz** [comment]
Sorry, I've made this a mess of several, only *possibly* related bugs, so I'm closing this. I'll try to understand the problems better, and if I get any meaningful results I'll open a new, clearer issue.

Of course you can reopen this if you want, since it's your repo, but currently (though I'm still not using kiwmi as my main WM/compositor) I think kiwmi is usable with the mirroring workaround (anyway, the best option for me would be turning the laptop screen off, but I already have an idea how to (ab)use it).

**Comment by buffet** [comment]
Huh, that's definitely interesting.

I haven't really figured out what's causing any of that yet.

**Comment by tiosgz** [comment]
Not that I think it’s enough to find out the cause, but anyway I’ve got some new info (though the issue has slightly changed in between):

When I see the grey screen, there’s also the cursor (nothing new) and what I’ve drawn in views’ `pre_render` (which I did not use until today; I guess it’s the same for `post_render`). In other words, kiwmi can render anything it wants, but only what’s its own, not what its clients want to show.

Now what’s changed:
* I use only the laptop w/o external monitor now
* it’s more often that it comes when I open a view or move the cursor to one; pressing a key usually fixes it until I do something else
* I’ve even seen it once when I started kiwmi under X11

What’s still the same:
* I can’t seem to find a system in when it happens; usually I check it on startup by just opening a terminal & when I get grey screen I quit & re-start kiwmi

**Comment by tiosgz** [comment]
`rdata->output_ly` seems to be the wrong one (I tried removing all the other things & this is the only one after which I couldn’t reproduce the flickering yet)

(Almost) obviously it also is the same problem in `render_layer_surface` above.

**Comment by buffet** [comment]
Oh, great work finding that!
