### ISSUE TITLE
Clipboard isn't implemented yet

### ISSUE THREAD

**Issue by buffet** [buffet/kiwmi#26]
If possible, also implement the other "simple to implement" protocols (dmabuf, gamma control, screencopy I think).

**Comment by 6gk** [comment]
plzfix(andstar)

**Comment by buffet** [comment]
@tiosgz I was told you had something for this, does it work and would you be willing to PR?

**Comment by tiosgz** [comment]
I’ve been using it for quite some time and it seems to work as expected.

I have some (few) other stuff on the [`mine` branch](<https://github.com/tiosgz/kiwmi/commits/mine>) that you may want to get merged as well (let me know here or any other way, I just need to know what you want & if you want it in any particular order). That branch is a bit messy, sorry.
