### ISSUE TITLE
View IDs

### ISSUE THREAD

**Issue by tiosgz** [buffet/kiwmi#28]
I need a simple way to identify views in my config. Can you please add something like view IDs?

I've tried to do this 'little change' myself, but can't seem to get it right.

Edit: It seems I just had an awful error in my `init.lua`, otherwise it could (or could not) have worked.

**Comment by buffet** [comment]
View IDs are something I tried to avoid. You should be able to just store references to them, and directly compare them (with ==). What's your exact usecase?

**Comment by tiosgz** [comment]
* custom properties — I need something to use as the key, and two references to the same view are different keys
* (later) placement in the layout

Why do you not want them to have IDs?

**Comment by buffet** [comment]
ID systems are just awkward when you already have refs.

You mean as keys in a table? That might be an issue, I'll check what we could do.

**Comment by tiosgz** [comment]
Just realised I can kind-of do this simply by keeping a table of all views & searching through it every time. I haven't yet adapted my config to it, but I think it'll work.

I'll let you know then, & I think if everything's OK this can be closed afterwards.

**Comment by tiosgz** [comment]
Tested now, seems to work pretty well.

Anyway, having it 'native' is still welcome at any time.
