### ISSUE TITLE
Fix issues in README.adoc

### ISSUE THREAD

**Issue by Qazzquimby** [buffet/kiwmi#6]
README.md could be more concise and contains typos.

**Comment by buffet** [comment]
I'll check for typos in a minute.

What do you think is missing from the readme, that would make it more concise?

**Comment by Qazzquimby** [comment]
I have a fix in progress.
I only added the issue because you asked for an issue for each pull request.
One moment.

**Comment by buffet** [comment]
Ah thanks, nice!
